apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: 3tier-application
spec:
  selector:
    app: 3tier-application
    tier: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP