apiVersion: v1
kind: ConfigMap
metadata:
  name: 3tier-application-config
  namespace: 3tier-application
data:
  ENVIRONMENT: "development"
  BACKEND_URL: "http://3tier-application-backend-service:5000"
  APP_NAME: "3tier-application"