apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: 3tier-application
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: RG-TEST
spec:
  selector:
    app: 3tier-application
    tier: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer