name: 3-Tier Application - Development CI

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:
  docker-build:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: 3tier-backend:ci

      - name: Build frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          tags: 3tier-frontend:ci
